### ISSUE TITLE
Error: Protocol error (Page.navigate): Invalid parameters Failed to deserialize params.url - BINDINGS: mandatory field missing at position 49

### ISSUE THREAD

**Issue by victimizing** [Zaarrg/TTVDropBot#32] opened 2021-09-04 06:31 UTC
Watching (twitch link here)

Reached 100 %... Looking for new Channel...

Checking for Live Channels

Going to Starting Channel...
(node:5276) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Invalid parameters Failed to deserialize params.url - BINDINGS: mandatory field missing at position 49
    at C:\Users\\OneDrive\Desktop\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\\OneDrive\Desktop\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16)
    at next (C:\Users\\OneDrive\Desktop\node_modules\puppeteer-extra-plugin-stealth\evasions\sourceurl\index.js:30:43)
    at CDPSession.send (C:\Users\\OneDrive\Desktop\node_modules\puppeteer-extra-plugin-stealth\evasions\sourceurl\index.js:46:18)
    at navigate (C:\Users\\OneDrive\Desktop\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:108:47)
    at FrameManager.navigateFrame (C:\Users\\OneDrive\Desktop\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:91:13)
    at Frame.goto (C:\Users\\OneDrive\Desktop\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:416:41)
    at Page.goto (C:\Users\\OneDrive\Desktop\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:789:53)
    at StreamPage (C:\Users\\OneDrive\Desktop\src\Pages\StreamPage.js:31:24)
(Use `TTVDropBot --trace-warnings ...` to show where the warning was created)
(node:5276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Zaarrg** [comment] 2022-02-09 18:54
Fixed by the latest [commit](https://github.com/Zaarrg/TTVDropBot/commit/8baeaed218582b29ae551a9a169b5e8e5112bcb3). Caused by one channel which was claimed being online and the bot removing it from the possible channels to watch list resulting in no channels to watch.

**Closed by Zaarrg** 2022-02-09 18:54 UTC
