### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate) 

### ISSUE THREAD

**Issue by MondoPIX** [Zaarrg/TTVDropBot#23] opened 2021-07-18 15:30 UTC
![ttv](https://user-images.githubusercontent.com/22109196/126073027-0fffd584-6f4a-40c5-bd7a-2de79706623f.png)

**Comment by tw0zh** [comment] 2021-07-18 16:10
Same

**Comment by tw0zh** [comment] 2021-07-18 16:13
![image](https://user-images.githubusercontent.com/26041065/126074452-f445b577-0d6b-4c4b-9ada-b6e1d58a73e4.png)

**Comment by Zaarrg** [comment] 2021-07-18 17:42
@tw0zh This error should be fixed in the [1.3.3.1 Release](https://github.com/Zaarrg/TTVDropBot/releases/tag/1.3.3.1).

@MondoPIX Can u check if you still get this error in 1.3.3.1, the error is caused because the bot can't open the channels url (https://twitch.tv/streamer). Could be either caused by your network not loading the page in, chrome crashing or not opening the tab... can't tell for sure, the only sure thing is that it fails at going to the streamers ch. (https://twitch.tv/streamer). Check [1.3.3.1](https://github.com/Zaarrg/TTVDropBot/releases/tag/1.3.3.1) if u still get this error.

**Comment by Pwnyhof** [comment] 2021-07-18 19:01
@Zaarrg using the 1.3.3.1 .exe only version still getting UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate)

**Comment by tw0zh** [comment] 2021-07-18 19:03
Yeah same as me

**Comment by MondoPIX** [comment] 2021-07-18 19:39
for the moment 1.3.3.1 does not give me any errors 😇

**Comment by Zaarrg** [comment] 2021-07-18 19:45
@Pwnyhof Do u also get the error when using the uncompressed version with the modules folder?
Can't recreate the error... For me the Bot runs just fine, also u could try using it as the nodejs version. Just follow the steps [here](https://github.com/Zaarrg/TTVDropBot#installation) for the npm version. Also try restarting your pc and manually opening chrome and checking if everything is fine on the twitch page

**Comment by tw0zh** [comment] 2021-07-18 19:51
@Zaarrg it happens when no one is online and the bot will wait 10 minutes to search other stream and if it doesn't get anyone live the error will happen after the 10 minutes, try it when the streamers are all offline

**Comment by Pwnyhof** [comment] 2021-07-18 19:56
@tw0zh exactly this problem I have after the bot waits the 10mins you get: UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate) error.

@Zaarrg I installed the module's version 40mins ago +- the bot is botting SONII's right now after the bot is done with him I will find out if I get the error or not, i will let you know.

**Comment by Pwnyhof** [comment] 2021-07-18 21:21
@Zaarrg looks like the uncompressed version works without any problem, it's just the standalone .exe version that spits out this error code.

**Comment by MondoPIX** [comment] 2021-07-18 22:20
> @Zaarrg it happens when no one is online and the bot will wait 10 minutes to search other stream and if it doesn't get anyone live the error will happen after the 10 minutes, try it when the streamers are all offline

![image](https://user-images.githubusercontent.com/22109196/126083809-c5a5df8a-693d-428e-b8d3-2e7bcef0041a.png)

for me its work

**Comment by tw0zh** [comment] 2021-07-18 22:21
@Pwnyhof thanks for letting me know it works.

**Comment by Zaarrg** [comment] 2021-07-18 23:50
@tw0zh Can u check this temp fix i made, should solve your issue for now, or more ingore it and let the bot work instead of crashing. Try this version: [TTVDropBot uncompressed tempfix](https://github.com/Zaarrg/TTVDropBot/raw/main/TTVDropBot%20uncompressed%20tempfix.zip)

**Comment by tw0zh** [comment] 2021-07-19 00:12
@Zaarrg thanks for the quick fix. I am running the bot on two different computers, my day to day computer and a vps, on the normal computer the 1.3.3.1 version works like a charm but on the vps running windows server 2012 r2 it keeps getting all sorts of errors. Unfortnatly I can't test right now your uncompressed tempfix because the vps is bussin but once its working I will give feedback.

**Comment by tw0zh** [comment] 2021-07-19 02:12
Still giving the error
![image](https://user-images.githubusercontent.com/26041065/126093033-ec9e112e-47e7-4ad6-ae20-805c4e684f67.png)

**Comment by Pwnyhof** [comment] 2021-07-19 11:44
@tw0zh Worked fine for 6hrs+- left it on overnight got the error again for some reason

**Comment by tw0zh** [comment] 2021-07-19 15:07
same

**Comment by TrapStoner** [comment] 2021-07-19 16:29
Yep it happens when no one is online. Left it overnight too and woke up to this 
![image](https://user-images.githubusercontent.com/14042777/126194541-54f9cdc5-f28d-4279-b006-91a8f73b4cab.png)

**Comment by tw0zh** [comment] 2021-07-19 17:02
@TrapStoner Exactly same thing to me

**Comment by Zaarrg** [comment] 2021-07-21 21:18
@tw0zh @TrapStoner Can someone of you try this version with the debug enabled and send me the full log, maybe then i can find the exact cause of the error, not really sure whats happening can not recreate the error, everything fine on my site... @TrapStoner The bot checks if all channels are offline and then show "All channels offline waiting 10mins for new ones to go online" ... And thought mabye if only one ch is online, but added a check for that and the error still happens for you so not really sure what the bot does there... Link to the debug logs added to the bot: https://mega.nz/file/3tBgFb4R#YO9q4hMJrf5dtmvnL73N9Ids858q6tljnmywIhi4OhM Somehow cant upload it here gives me an error.

**Comment by tw0zh** [comment] 2021-07-22 17:31
@Zaarrg tried it last night and for some weird reason I got a timeout error but I will try it again, I know that this error also happens while using the custom channel setting.

**Comment by TrapStoner** [comment] 2021-07-22 21:03
I am sorry i was busy and couldn't try it before the round got over, but if there is a way to help still i would be glad to do it.

**Comment by TrapStoner** [comment] 2021-09-03 15:19
Once again i woke up to the same issue 
![image](https://user-images.githubusercontent.com/14042777/132029115-d6d1acd3-09ac-4f2c-aa87-c8b3dc046690.png)

**Comment by Zaarrg** [comment] 2022-02-06 22:16
Not active anymore, if this still occurs you can reopen this issue. (Navigation timeout is fixed)

**Closed by Zaarrg** 2022-02-06 22:16 UTC
Labels: issue
