### ISSUE TITLE
Cannot read get property "getProperty" of undefined

### ISSUE THREAD

**Issue by arisawali2014** [Zaarrg/TTVDropBot#4] opened 2021-03-10 03:30 UTC
![image](https://user-images.githubusercontent.com/31904944/110572217-97abfb80-818b-11eb-82e8-417faceab826.png)
i got this error after getting twitch channel

**Comment by Zaarrg** [comment] 2021-03-10 10:31
Fixed in Release 1.2-hotfix
Caused by Design change of 'https://twitch.facepunch.com/' which caused xpaths to be invaild

**Closed by Zaarrg** 2021-03-10 10:31 UTC
